MARKET = 'BTCUSDT'



MIN_LIMIT_ORDERBOOK_DATA = 50
MAX_LIMIT_ORDERBOOK_DATA = 500
MIN_RELATIVE_THRESHOLD_DIV = 2
MAX_RELATIVE_THRESHOLD_DIV = 200
MIN_THESHOLD_SHORT = 0.55
MAX_THESHOLD_SHORT = 0.9

MIN_THESHOLD_LONG = 0.1
MAX_THESHOLD_LONG = 0.45

MIN_MAX_SECONDS_TRADE_OPEN = 10
MAX_MAX_SECONDS_TRADE_OPEN = 2000

MIN_PEAK_DISTANCE_DIVISOR = 2
MAX_PEAK_DISTANCE_DIVISOR = 200

MIN_SL_PRICE_BUFFER = 0.01
MAX_SL_PRICE_BUFFER = 2.0

MIN_TP_PRICE_BUFFER = 0.01
MAX_TP_PRICE_BUFFER = 2.0

MIN_PERCENTAGE_PER_TRADE = 0.001 # 0.1 %
MAX_PERCENTAGE_PER_TRADE = 0.05 # 5%