MIN_LIMIT_ORDERBOOK_DATA = 50
MAX_LIMIT_ORDERBOOK_DATA = 500

MIN_RELATIVE_THRESHOLD_DIV = 2
MAX_RELATIVE_THRESHOLD_DIV = 100

MIN_THRESHOLD_SHORT = 0.55
MAX_THRESHOLD_SHORT = 0.7

MIN_THRESHOLD_LONG = 0.3
MAX_THRESHOLD_LONG = 0.45

MIN_MAX_SECONDS_TRADE_OPEN = 10
MAX_MAX_SECONDS_TRADE_OPEN = 2000

MIN_PEAK_DISTANCE_DIVISOR = 2
MAX_PEAK_DISTANCE_DIVISOR = 100

MIN_SL_PRICE_BUFFER = 0.01
MAX_SL_PRICE_BUFFER = 2.0

MIN_TP_PRICE_BUFFER = 0.01
MAX_TP_PRICE_BUFFER = 2.0

MIN_PERCENTAGE_PER_TRADE = 0.98 # 0.1 %
MAX_PERCENTAGE_PER_TRADE = 0.99 # 5%

MIN_K = 1
MAX_K = 10

MIN_WINDOW_INCREMENT = 10
MAX_WINDOW_INCREMENT = 150

